site_name: Holocron

theme:
  name: material
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/lightbulb-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: black
    accent: teal
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: black
    accent: teal
    toggle:
      icon: material/lightbulb-outline
      name: Switch to system preference
  features:
  - content.code.annotate
  - content.code.copy
  - content.code.select
  - content.footnote.tooltips
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.preview
  - navigation.instant.progress
  - navigation.path
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  - toc.follow

nav:
  - Holocron: 
    - index.md

  - Python:
    - python/index.md
    - python/uv.md
    - python/scaffolding.md
    - python/builtin_functions.md
    - Standard library:
      - python/stdlib/index.md
      - python/stdlib/data_structures.md
      - python/stdlib/files_archives.md
      - python/stdlib/datetime.md
      - python/stdlib/math.md
      - python/stdlib/cli.md
      - python/stdlib/networking.md
      - python/stdlib/security_hashing_compression.md
      - python/stdlib/serialization_persistence.md
    - python/file_handling.md
    - python/exception_handling.md
    - python/lambdas.md
    - python/io.md
    - python/oop.md
    - python/fp.md
    - python/sorted.md
    - python/magic_methods.md
    - python/iterators.md
    - python/generators.md
    - python/decorators.md
    - python/context_manager.md
    - python/callbacks.md
    - python/multithreading.md
    - python/multiprocessing.md
    - python/asyncio.md
    - python/memmory_management.md
    - python/metaclasses.md
    - python/descriptors.md
    - python/eval.md
    - python/exec.md

  - TS:
    - ts/index.md

  - SvelteKit:
    - svelte/index.md

  - PyTorch:
    - pytorch/index.md

  - Docker:
    - docker/index.md

  - K8s:
    - k8s/index.md

  - GCP:
    - gcp/index.md

  - Postgres:
    - postgres/index.md

  - Redis:
    - redis/index.md